config/routes.rb
Glitter::Application.routes.draw do

  resources :users, :projects
  resource :session, only: [:new, :create, :destroy]
  resource :comments
  resources :glitterposts 


  get 'projects/:id/commits' => 'projects#commits'
  get 'projects/:id/commit/:tree_id' => 'projects#projectcommit'
  get 'projects/:id/masterbranch/:image_name' => 'projects#masterbranch', :image_name => /[^\/]*/
  get 'projects/:id/masterbranch/:image_name/history' => 'projects#file_history', :image_name => /[^\/]*/
  get 'projects/:id/createsvg' => 'projects#new_svg'
  get 'projects/:id/masterbranch/:image_name/edit' => 'projects#edit_svg', :image_name => /[^\/]*/

  resources :projects do
    member do
      get 'projects/:id/invite.xml' => 'projects#invite'
      get 'projects/:id/fork' => 'projects#fork'
      get 'projects/:id/forkyou' => 'projects#forkyou'
      post :file_upload
      post :file_update
      post :create_svg, :as => :create_svg
    end
  end

  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete

  get 'dashboard/' => 'dashboard#index', :as => :dashboard

  root :to => 'sessions#new'

end

app/controllers/dashboard_controller.rb
# This controller defines interactions with the user's dashboard.
# New methods should be added to this controller as the application
# becomes more powerful.

class DashboardController < ApplicationController

  def index
    @projects = current_user.projects
    unless @projects.count == 0
      #@glimages = current_user.glimages
    else
      redirect_to new_project_path
    end
  end
end

app/views/dashboard/_projectlist.html.haml
%h2
  My Projects
%ul#myprojects
  - @projects.each do |p|
    %li
      .project-thumb
        =  # link_to url_for(p) do
        - # FIXME
        - # Once the Glimage model drop isn't causing any ugly consequences,
        - # fix this so it works normally. 

      %h3
        = link_to p.name, url_for(p)
      .meta
        Created
        -# um, this evalutes backwards, i'm not sure why
        - if p.created_at > 1.year.ago
          = time_tag p.created_at, :format=>'%B %d'
        - else 
          = time_tag p.created_at, :format=>'%B %d, %Y'
        %br
        Last updated
        = distance_of_time_in_words_to_now p.updated_at
        ago

      

app/views/dashboard/index.html.haml
-#
  Show the user's dashboard.
  Currently only has the upload image form
  and the path to the user's repo

- content_for :title do
  Dashboard

= render 'shared/glimageshow'

.center
  #dashboard
    = render 'projectlist'
          
  #sidebar
    %h2 toolbox
    %ul
      %li
        = link_to 'Add a new project', new_project_path
      -# %li#repo_link
        = File.expand_path @user.repo.path
      %li
        = link_to 'Write a glitterpost!', new_glitterpost_path
        