config/routes.rb
Glitter::Application.routes.draw do

  resources :users, :projects
  resource :session, only: [:new, :create, :destroy]
  resource :comments
  resources :glitterposts 


  get 'projects/:id/commits' => 'projects#commits'
  get 'projects/:id/commit/:tree_id' => 'projects#projectcommit'
  get 'projects/:id/masterbranch/:image_name' => 'projects#masterbranch', :image_name => /[^\/]*/
  get 'projects/:id/masterbranch/:image_name/history' => 'projects#file_history', :image_name => /[^\/]*/
  get 'projects/:id/createsvg' => 'projects#new_svg'
  get 'projects/:id/masterbranch/:image_name/edit' => 'projects#edit_svg', :image_name => /[^\/]*/

  resources :projects do
    member do
      get 'projects/:id/invite.xml' => 'projects#invite'
      get 'projects/:id/fork' => 'projects#fork'
      get 'projects/:id/forkyou' => 'projects#forkyou'
      post :file_upload
      post :file_update
      post :create_svg, :as => :create_svg
    end
  end

  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete

  get 'dashboard/' => 'dashboard#index', :as => :dashboard

  root :to => 'sessions#new'

end

app/models/glitterpost.rb
class Glitterpost < ActiveRecord::Base
  attr_accessible :content, :title
  belongs_to :user

  validates :content, presence: true
  validates :title, presence: true
end

app/controllers/glitterposts_controller.rb
# User interacts with glitterposts through the methods defined 
# in this controller. 
# User may create multiple unique glitterposts and share them with
# others! This controller is guaranteed to require lots of improvements, 
# in the future, we may have to consider replacing this with a blogging
# system out of a good gem.

class GlitterpostsController < ApplicationController

  # New glitterposts can be created  in the glitterposts#new page. 
  # We're currently asking just for the title and content.

  def new
  end

  # Glitterpost creation is defined in the method below. We're allowing 
  # them to add a title and content to it and we're then adding them to the glitterpost 
  # list of the person who's currently logged in.

  def create
  	@glitterpost = Glitterpost.new(params[:glitterpost])
  	@glitterpost.user_id = current_user.id
  	if @glitterpost.save
  		redirect_to @glitterpost
  	else
      flash[:alert] = "Something went wrong, try glitterposting again."
  		render 'new'
  	end
  end

  # Glitterposts may be edited through this function. Title and content appears on a form
  # so they can be changed easily, the current state appearing as the current text.
  # Only authors of glitterposts are allowed to edit them.

  def edit
    @glitterpost = Glitterpost.find(params[:id])
  end

  # Used by glitterpost#edit to update glitterposts.

  def update
    @glitterpost = Glitterpost.find(params[:id])
    if @glitterpost.update_attributes(params[:glitterpost])
      redirect_to @glitterpost
    else
      render 'edit'
    end
  end

  # Used for displaying a feed of all glitterposts ever made on GlitterGallery.

  def index
  	@glitterposts = Glitterpost.all
  end
  
  # Displays the glitterposts with the specified id at /glitterposts/:id;
  # comments for the glitterpost are included. 

  def show
  	@glitterpost = Glitterpost.find(params[:id])
    @comments = Comment.where(polycomment_type: "glitterpost", polycomment_id: @glitterpost.id)
    
  end

  # Deltes a glitterposts forever. Only author is allowed to delete.

  def destroy
  	@glitterpost = Glitterpost.find(params[:id])
  	@glitterpost.destroy
  	redirect_to glitterposts_path
  end

end

app/views/glitterposts/edit.html.haml
.title
  Edit this Glitterpost #{link_to '(or go back to the Glitterposts)', glitterposts_path }

= form_for @glitterpost do |f|
  - if @glitterpost.errors.any?
    %p
      #{pluralize(@glitterpost.errors.count, "error")} prohibited this post from being saved
    %ul
    = @glitterpost.errors.full_messages.each do |msg|
      %li
        = msg 
  %p.input
    = f.label :title 
    = f.text_field :title 
 
  %p.input
    = f.label :content
    = f.text_area :content  

  %p.submit
    = f.submit
 

app/views/glitterposts/index.html.haml
#glitterposts
  - @glitterposts.each do |post| 
    .glitterpost
      .glitterpost-meta
        = avatar(User.find(post.user_id).email)
      %p.title.padded
        = link_to post.title, post

app/views/glitterposts/new.html.haml
.title
  Create a new glitterpost! #{link_to '(or go back to the Glitterposts)', glitterposts_path }
= form_for :glitterpost, url: glitterposts_path do |f|
  %p.input
    Title
    = f.text_field :title
  %p.input
    Content
    = f.text_area :content 
  %p.submit
    = f.submit  
  

app/views/glitterposts/show.html.haml
- content_for :title do
  = @glitterpost.title.titleize
#glitterposts
  .glitterpost
    .glitterpost-meta
      = avatar(User.find(@glitterpost.user_id).email)
      %p.author.padded
        Posted by #{User.find(@glitterpost.user_id).username} #{distance_of_time_in_words_to_now @glitterpost.created_at} ago
      %p.title.padded
        = @glitterpost.title
    .glitterpost-body
      = @glitterpost.content
    
#operations
  .operation
    = link_to 'Back', glitterposts_path
  - if logged_in? && (@glitterpost.user_id == current_user.id)
    .operation
      = link_to 'Edit', edit_glitterpost_path
    .operation
      = link_to 'Destroy', glitterpost_path, method: :delete, data: { confirm: 'Are you sure?' }

.center
  #comments
    - @comments.each do |comment|
      - if comment.user_id == @glitterpost.user_id
        = render 'comments/comment_author', :comment => comment
      - elsif logged_in? and comment.user_id == current_user.id
        = render 'comments/comment_current', :comment => comment
      - else 
        = render 'comments/comment_normal'
    = render 'comments/new'


    .comment-body
      = form_for Comment.new do |f|
        = hidden_field_tag 'polycomment_type', 'glitterpost'
        = hidden_field_tag 'polycomment_id',  @glitterpost.id.to_s
        .comment_field
          = f.text_field :body, :placeholder => 'Add your comment...'
        .submit
          = f.submit 