config/routes.rb
Glitter::Application.routes.draw do

  resources :users, :projects
  resource :session, only: [:new, :create, :destroy]
  resource :comments
  resources :glitterposts 


  get 'projects/:id/commits' => 'projects#commits'
  get 'projects/:id/commit/:tree_id' => 'projects#projectcommit'
  get 'projects/:id/masterbranch/:image_name' => 'projects#masterbranch', :image_name => /[^\/]*/
  get 'projects/:id/masterbranch/:image_name/history' => 'projects#file_history', :image_name => /[^\/]*/
  get 'projects/:id/createsvg' => 'projects#new_svg'
  get 'projects/:id/masterbranch/:image_name/edit' => 'projects#edit_svg', :image_name => /[^\/]*/

  resources :projects do
    member do
      get 'projects/:id/invite.xml' => 'projects#invite'
      get 'projects/:id/fork' => 'projects#fork'
      get 'projects/:id/forkyou' => 'projects#forkyou'
      post :file_upload
      post :file_update
      post :create_svg, :as => :create_svg
    end
  end

  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete

  get 'dashboard/' => 'dashboard#index', :as => :dashboard

  root :to => 'sessions#new'

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      GlitterGallery! 
      - if content_for?(:title)
        |
        = yield :title
    
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tag
    %script
      $(function() { jQuery('#glittercarousel').jcarousel({ wrap: 'circular'  }); });

  %body{ :class => "#{controller.controller_name} #{controller.action_name} #{logged_in? ? 'logged_in' : 'not_logged_in'} #{yield :body_class}" }

  
    %header
      %nav#user_nav
        - if logged_in?
          .welcome
            %span.msg
              >
            %span.email
              = link_to current_user.username + "'s dashboard", dashboard_path
          - if controller.controller_name != 'home'
            = link_to root_url do
              %h1.logo
                Glitter Gallery
          .right
            - if controller.controller_name != 'dashboard'
              = link_to 'Dashboard', dashboard_path 
            = link_to 'Logout', logout_path, :method => :delete
        - else
          #login_prompt
            = link_to 'Login', login_path
      = yield :header
      
    = yield
    